### PR TITLE
Fix ContactsController, App.Routes test

### PR DESCRIPTION
**Pull request by msauza**
Issue ref #16 

_Add $onInit function to pass contacts, filter values to contactsFilter's constructor.
Call $onInit function for controller initialization.
Rename 'ConctactController' test name to 'ContactsController'._

Issue ref #18 

_Change url definition for contacts state app/contacts -> /app/contacts._

### CODE REVIEW

**Comment by SiGroves** [comment]
Sorry, but I seem to have failed the course because I don't understand what this fix is?
I am finding the problem: vendor.js:14525 TypeError: Cannot read property 'filter' of undefined
    at contacts.filter.js:5.

What code do I need to resolve this?

**Comment by toddmotto** [comment]
If you're using Angular 1.5 then you don't need to worry about the fix @SiGroves - but for 1.6, the only change you need to make is dropping the code inside the `$onInit` lifecycle hook instead of just part of the controller outside of the lifecycle hook. There's a new note that's been added at the beginning of the course "1.6 breaking changes" which explains a little further, more [here](https://toddmotto.com/angular-1-6-is-here) too. Hope that answers it for you :)!

**Comment by SiGroves** [comment]
Sorry, Todd.
That's no help to me.
I'm still learning!!
I saw your note which led me to this "fix".
I'm using your Gulp - I don't know what version of Angular I'm using. But I guess it's 1.6 otherwise I wouldn't get the error?

Are you saying I need to make a change to this file contacts.filter.js:
function contactsFilter() {
  return function (collection, params) {
    return collection.filter(function (item) {
      return item.tag === (
        params.filter === 'none' ? item.tag : params.filter
      );
    });
  };
}

angular
  .module('components.contact')
  .filter('contactsFilter', contactsFilter);

And if I understand correctly, I need to create an OnInit in there?
to do what? and to replace what?

Simon

**Comment by toddmotto** [comment]
No problem @SiGroves ! So the `$onInit` lifecycle hook gets called when:

- Component is initialised
- When incoming data properties are "ready"

In our case, `ctrl.contacts` and `ctrl.filter` are properties on the component's controller that are driven from the route resolve - so they are _only_ ready inside `$onInit`. In Angular 1.5 this wasn't the situation as they'd be available outside of this "initialisation" hook.

Essentially, you just need to wrap it inside the hook to make sure those above properties are available [like this](https://github.com/toddmotto/angular-1-5-components-app/blob/646ce5ec52d59a05776da0e8dbae8fc217dff2be/src/app/components/contact/contacts/contacts.controller.js#L4-L6).

**Comment by SiGroves** [comment]
aha!
OK I see now.
Thanks for your rapid response!
Keep up the good work!
Thanks for all your help in the video tutorials.

**Comment by toddmotto** [comment]
Awesome! Thanks for the kind words @SiGroves :) ciao for now and good luck with the rest of the course!

**Pull request merged**
