### PR TITLE
Change links without hrefs to buttons

### PR DESCRIPTION
**Pull request by marcin-pajak**
Link without href is an antipattern and should be avoided, especially in demo apps

### CODE REVIEW

**Comment by toddmotto** [comment]
Appreciate the PR, why is this considered an antipattern?

Using `<a href="">Press me</a>` automatically prevents default, as `<a>` tags are actually AngularJS directives, from the source:

``` js
var htmlAnchorDirective = valueFn({
  restrict: 'E',
  compile: function(element, attr) {
    if (!attr.href && !attr.xlinkHref) {
      return function(scope, element) {
        // If the linked element is not an anchor tag anymore, do nothing
        if (element[0].nodeName.toLowerCase() !== 'a') return;

        // SVGAElement does not use the href attribute, but rather the 'xlinkHref' attribute.
        var href = toString.call(element.prop('href')) === '[object SVGAnimatedString]' ?
                   'xlink:href' : 'href';
        element.on('click', function(event) {
          // if we have no href url, then don't navigate anywhere.
          if (!element.attr(href)) {
            event.preventDefault();
          }
        });
      };
    }
  }
});
```

**Comment by marcin-pajak** [comment]
Thanks for a quick response.

It’s not just about preventDefault. There are two more major problems:

First one when you don’t include href attribute (you did, but someone who had seen your example can forget), then such link is not accessible from the keyboard unless you add tabindex to it, and there is no cursor pointer when hovering.

Second one - browsers show context menu with all link related options in such case, which also generates potential problems, like questions why open in new tab doesn’t work, why save as bookmark crashed when trying to open, why copy link doesn’t work when sharing it with coworker etc

So it’s considered better to use links with valid href only, although the ones without href are also ‘valid' html.

**Comment by typeofweb** [comment]
It's also an antipattern simply because **it's against the semantics of `a` and `button`**.

As defined in HTML5 specification, [anchors](https://www.w3.org/TR/html5/text-level-semantics.html#the-a-element) are supposed to allow users to navigate to resources (i.e. visit in a browser or download). On the other hand, buttons are supposed to represent... [buttons](https://www.w3.org/TR/html5/forms.html#the-button-element).

Good examples of `<a>`:
- link to profile page
- "home" link
- a link which triggers download of a pdf file

Bad examples of `<a>`:
- log out button
- add/remove item buttons

**Comment by mikeerickson** [comment]
That merge was by complete accident, fat fingered on my iPhone reading this issue

Todd, please revert accordingly should you choose.  

My apologies :)

**Pull request merged**
