### PR TITLE
SCSS Project Architure, Styling improvements & Dgeni Documentation Generator

### PR DESCRIPTION
**Pull request by eHxBes**
**Small visual improvements we're implemented, here's a list of changes:**
- Login error message now has the same visual presentation as others (red coloring)
- Login error now has better spacing from password input
- Implemented maps to group color variables together
- Button (hover, focus, active) states now are visually different from the default state
- Organize & Structure SCSS files into separate files for each 'component' 
  - _It would also promote best practices for project structure_

**Here's a couple of other things we could do:**
- Make the app-sidebar smaller on smaller viewports
- Show more details in the 'list' view (add job title, location, etc...) 
  - _That way, the detail / edit view would only be for editing_
- Add 'for' and 'ids' so that you can click on the form labels and it focuses on the input
  - _better UX & accessibility_
- Have a function that 'generates' 10 random contacts and adds them to the list. 
  - _We could use this opportunity to showcase the number of $watchers per page, and users would see how performant a component based architecture really is_
- Would be cool to have 'pictures' for each contact

### CODE REVIEW

**Comment by eHxBes** [comment]
Added the SCSS architecture! :)

**Comment by eHxBes** [comment]
Added the Dgeni documentation generator so we can document the app

**Comment by toddmotto** [comment]
Merging #yolo

**Comment by blowsie** [comment]
Great effort, except I'm not sure how useful documentation with lorem ipsum text really is.
@sebpelletier are you planning to document the application?

**Comment by eHxBes** [comment]
Actually, the documentation was pushed for an article on Todd's blog -> [https://toddmotto.com/documenting-angular-dgeni](url)

The Lorem Ipsum text was added to show how the tool works, and not necessarily to completely document the application. 

It occured to me that this app should be documented thoroughly, but all the implementation details are actually in the Angular 1.x Pro course on [https://ultimateangular.com/angular-1-pro](url), and this repo serves as the final product of what people should be creating while following the course.

Eventually I should have a talk with @toddmotto to discuss if we should document this app a bit more :)

**Pull request merged**
